# -*- coding: utf-8 -*-
"""readMatricesExcelAndHowtoRead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOfdED04IE0SEZRtfvcH7F8zuFi4fLDY
"""

#pip install pandas openpyxl    VREY IMPORTANT!

import pandas as pd
import numpy as np

def read_matrices(filename, sheet_name='Sheet1'):    #Sheet 1 is the default setting
    # Read only the first few rows where data is expected
    df = pd.read_excel(filename, sheet_name=sheet_name)

    # Initialize the list to store matrices and the start column index
    matrices = []
    start_col = 0

    # Detect where the columns are completely NaN to find breaks between matrices
    while start_col < df.shape[1]:
        # Ignore initial empty columns if any
        if df.iloc[:, start_col].isna().all():
            start_col += 1
            continue

        # Find the next all-NaN column which signifies the end of a matrix
        end_col = start_col
        while end_col < df.shape[1] and not df.iloc[:, end_col].isna().all():
            end_col += 1

        # Extract the matrix between start_col and end_col, minus one to exclude the NaN column
        matrix_df = df.iloc[:, start_col:end_col].dropna(how='all', axis=1)
        matrices.append(matrix_df.values)  # Convert DataFrame to NumPy array

        # Update start_col to the column after the next NaN column
        start_col = end_col + 1

    return matrices


#Reading Process Example
filename = 'path'  # Update with the path to your Excel file
matrices = read_matrices(filename)

if len(matrices) >= len:   #Numbers of the expected matrices
    E, F, G, H = matrices[0], matrices[1], matrices[2], matrices[3]  #Assume there are four matrices
else:
    print("Error: Not enough matrices available in the list.")  # Throw out Exception